language: ruby
rvm:
- 2.2.5
deploy:
  provider: heroku
  api_key:
    secure: hICr5X1Kpz9HnuaO6H8I2Qzw7qS0z9ZV74me2QnMUGfx0l/D2vUiA6VFH+vnN8eraY6ySr5KrI/jy9VD9tlSIzEX8OyIIFhakbo6uecBrlue8TqHJFoe2C+4M51NSEeO6C/4EXS0leYgggkiE1dp6mof/tARaVjFxTE2p0LTsAvojtKCih+xdxLckY8p8xW4DDSniKCw7gHOvdmSM1FYtSnHlEWUyfecFWpNiKhu+/Efj0iyaZwUeRr9cXvSP1v1WW7u4jDWFElemXo6zVRy4LZH/zwLiVcfai+kkzj1TNjHlYAxRSWL98jSewUNHpndaf7G/EeygyWWM3GNQZVB4AQWWtcY48ARL+n77QtydPRmykvL00DnWvNlp4yg6xxAjv0gpULEBUNyYiepR+MP0tzZhCgRbktUsSkMSrVbWGoARRCxQac1Z3ZRr3TWdkur93u//5fONMAEgsxqw56+RdJp7tkP8Hq7sh0yUGxjln7TMvILJ3/JU7y2OmLVqfD1En1o34WVSA911FHlFVICmufZXEPLhaetEufuSEdkDGeTt6nrMrM/i7oYzySqxv+O+wATZG2dYKSJf1/6n675Fh1xvda+OaKJCwgDLG26DpPu/49l2hZQvJH5Y4AH+G+XQGz62mcXjrS1DEHyURQLlSoHcHkryLtFxZengKI4Ixg=
  app: radiant-everglades-60161
  on:
    repo: e125762/rakuten_enpit_example
